MVC_projekt/Models/Author.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using Resources;

namespace MVC_projekt.Models
{
    public class Author
    {

        public int AuthorID { get; set; }

        [Display(Name = "FirstName", ResourceType = typeof(Global))]
        public string Name { get; set; }

        [Display(Name = "Surname", ResourceType = typeof(Global))]
        public string Surname { get; set; }

        [NotMapped]
        [Display(Name = "Author", ResourceType = typeof(Global))]
        public string FullName {
            get { return this.Surname + " " + this.Name; } }

        public virtual ICollection<AuthorGroup> AuthorGroups { get; set; }
    }
}

MVC_projekt/Controllers/AuthorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MVC_projekt.Models;
using MVC_projekt.Models.Classes;

namespace MVC_projekt.Controllers
{
    [Localization("pl")]
    public class AuthorsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Authors
        public ActionResult Index()
        {
            return View(db.Authors.ToList());
        }

        // GET: Authors/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Author author = db.Authors.Find(id);
            if (author == null)
            {
                return HttpNotFound();
            }
            return View(author);
        }

        // GET: Authors/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Authors/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "AuthorID,Name,Surname")] Author author)
        {
            if (ModelState.IsValid)
            {
                db.Authors.Add(author);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(author);
        }

        public JsonResult Add(string name, string surname)
        {
            if (!db.Authors.Any(x => x.Name.ToLower().Equals(name.ToLower()) && x.Surname.ToLower().Equals(surname.ToLower())))
            {
                db.Authors.Add(new Author() { Name = name, Surname = surname });
                db.SaveChanges();

                var author = db.Authors.Single(x => x.Name.Equals(name) && x.Surname.Equals(surname));
                return Json(author);
            }
            return null;
        }

        // GET: Authors/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Author author = db.Authors.Find(id);
            if (author == null)
            {
                return HttpNotFound();
            }
            return View(author);
        }

        // POST: Authors/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "AuthorID,Name,Surname")] Author author)
        {
            if (ModelState.IsValid)
            {
                db.Entry(author).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(author);
        }

        // GET: Authors/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Author author = db.Authors.Find(id);
            if (author == null)
            {
                return HttpNotFound();
            }
            return View(author);
        }

        // POST: Authors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Author author = db.Authors.Find(id);
            db.Authors.Remove(author);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MVC_projekt/Controllers/BookItemsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Migrations;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using MVC_projekt.Models;
using MVC_projekt.Models.Classes;
using MVC_projekt.Models.Helpers;
using MVC_projekt.Models.View;
using PagedList;

namespace MVC_projekt.Controllers
{
    [Localization("pl")]
    public class BookItemsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private ViewTools vt = new ViewTools();

        // GET: BookItems
        public ActionResult Index(int? page)
        {
            int currentPage = page ?? 1;
            int onPage = 5;

            List<BookItem> bookItemList = db.BookItems.OrderBy(x=>x.BookItemID).ToList();

            return View(bookItemList.ToPagedList<BookItem>(currentPage, onPage));
        }

        // GET: BookItems/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BookItem bookItem = db.BookItems.Find(id);

            if (bookItem == null)
            {
                return HttpNotFound();
            }
            var av = bookItem.Number - db.Orders.Count(o => o.BookItemID == bookItem.BookItemID && !o.Returned);
            ViewBag.Available = av;
            return View(bookItem);
        }

        [Authorize(Roles = "Admin, Employee")]
        // GET: BookItems/Create
        public ActionResult Create()
        {

            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "Name");
            ViewBag.Authors = new SelectList(vt.GetAuthorsFromDb(db), "Value", "Text");
            ViewBag.Labels = new SelectList(db.Labels, "LabelID", "Name");
            return View();
        }

        // POST: BookItems/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(BookItemViewModel bookItem, HttpPostedFileBase cover, HttpPostedFileBase tableOfContents)
        {
            if (ModelState.IsValid)
            {
                if (!db.BookItems.Any(b => b.ISBN == bookItem.ISBN))
                {
                    vt.CreateBookItem(bookItem, db, cover, tableOfContents);
                    return RedirectToAction("Index");
                }
                else
                {
                    ViewBag.Error = true;
                    ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "Name");
                    ViewBag.Authors = new SelectList(vt.GetAuthorsFromDb(db), "Value", "Text");
                    ViewBag.Labels = new SelectList(db.Labels, "LabelID", "Name");

                    return View(bookItem);
                }
            }

            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "Name");
            ViewBag.Authors = new SelectList(vt.GetAuthorsFromDb(db), "Value", "Text");
            ViewBag.Labels = new SelectList(db.Labels, "LabelID", "Name");

            return View(bookItem);
        }

        [Authorize(Roles = "Admin, Employee")]
        // GET: BookItems/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BookEditViewModel bookItem = vt.GetBookEditViewModel(db.BookItems.Include(x => x.Category).Single(x => x.BookItemID == id), db);
            

            if (bookItem == null)
            {
                return HttpNotFound();
            }

            if (Request.UrlReferrer != null)
            {
                bookItem.BookItemViewModel.PreviousPage = Request.UrlReferrer.ToString();
            }
            else
            {
                bookItem.BookItemViewModel.PreviousPage = Request.Url.GetLeftPart(UriPartial.Authority);
            }
            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "Name");
            ViewBag.Authors = new SelectList(vt.GetAuthorsFromDb(db), "Value", "Text");
            ViewBag.Labels = new SelectList(db.Labels, "LabelID", "Name");
            ViewBag.Init = true;

            return View(bookItem);
        }

        // POST: BookItems/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(BookEditViewModel bookView, HttpPostedFileBase coverImg, HttpPostedFileBase tableOfContents)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    BookItem bookItem = vt.EditBookItem(bookView, db, coverImg, tableOfContents);
                    db.Entry(bookItem).State = EntityState.Modified;
                    db.SaveChanges();
                }
                else
                {
                    ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "Name");
                    ViewBag.Authors = new SelectList(vt.GetAuthorsFromDb(db), "Value", "Text");
                    ViewBag.Labels = new SelectList(db.Labels, "LabelID", "Name");
                    ViewBag.Init = true;
                    ViewBag.Error = true;
                    return View(bookView);
                }
            }
            catch (Exception)
            {

                ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "Name");
                ViewBag.Authors = new SelectList(vt.GetAuthorsFromDb(db), "Value", "Text");
                ViewBag.Labels = new SelectList(db.Labels, "LabelID", "Name");
                ViewBag.Init = true;
                ViewBag.Error = true;
                return View(bookView);
            }
            
            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "Name");
            ViewBag.Authors = new SelectList(vt.GetAuthorsFromDb(db), "Value", "Text");
            ViewBag.Labels = new SelectList(db.Labels, "LabelID", "Name");
            ViewBag.Error = false;
            ViewBag.Init = false;
            return View(bookView);
        }

        [Authorize(Roles = "Admin, Employee")]
        // GET: BookItems/Delete/5
        public ActionResult Delete(int? id, bool? error)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BookItem bookItem = db.BookItems.Find(id);

            if (bookItem == null)
            {
                return HttpNotFound();
            }

            if (error != null)
            {
                ViewBag.Error = true;
            }

            return View(bookItem);
        }

        // POST: BookItems/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                BookItem bookItem = db.BookItems.Single(x => x.BookItemID == id);
                db.BookItems.Remove(bookItem);
                var directory = Path.Combine(Path.Combine("/Upload", id.ToString()));
                if (Directory.Exists(directory))
                {
                    Directory.Delete(directory);
                }

                db.SaveChanges();
            }
            catch (Exception)
            {
                
                return RedirectToAction("Delete", new {id = id, error = true});
            }
            
            return RedirectToAction("Index");
        }


        public FileResult Download(string filename, string bookID, string source)
        {
            var directory = Path.Combine(Path.Combine("/Upload", bookID));
            var filepath = Path.Combine(directory, source);
            var contentType = "application/" + Path.GetExtension(filepath);
            return File(filepath, contentType, filename);
        }

        #region Order
        [HttpPost]
        public ActionResult Order(int id)
        {
            CartTools ct = new CartTools();
            ct.AddToCart(this.HttpContext, id);

            return RedirectToAction("Details", new {id});
        }

        [HttpPost]
        public ActionResult ReturnOrder(int id)
        {
            CartTools ct = new CartTools();
            ct.ReturnOrder(id);

            return RedirectToAction("Index");
        }
        #endregion

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MVC_projekt/Controllers/LabelsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MVC_projekt.Models;

namespace MVC_projekt.Controllers
{
    public class LabelsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Labels
        public ActionResult Index()
        {
            return View(db.Labels.ToList());
        }

        // GET: Labels/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Label label = db.Labels.Find(id);
            if (label == null)
            {
                return HttpNotFound();
            }
            return View(label);
        }

        // GET: Labels/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Labels/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "LabelID,Name")] Label label)
        {
            if (ModelState.IsValid)
            {
                db.Labels.Add(label);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(label);
        }

        public JsonResult Add(string name)
        {
            if (!db.Labels.Any(x => x.Name.ToLower().Equals(name.ToLower())))
            {
                db.Labels.Add(new Label() { Name = name });
                db.SaveChanges();

                var label = db.Labels.Single(x => x.Name.Equals(name));
                return Json(label);
            }
            return null;
        }

        // GET: Labels/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Label label = db.Labels.Find(id);
            if (label == null)
            {
                return HttpNotFound();
            }
            return View(label);
        }

        // POST: Labels/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "LabelID,Name")] Label label)
        {
            if (ModelState.IsValid)
            {
                db.Entry(label).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(label);
        }

        // GET: Labels/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Label label = db.Labels.Find(id);
            if (label == null)
            {
                return HttpNotFound();
            }
            return View(label);
        }

        // POST: Labels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Label label = db.Labels.Find(id);
            db.Labels.Remove(label);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MVC_projekt/Views/BookItems/Author.cshtml
@using MVC_projekt.Controllers
@using PagedList.Mvc
@model PagedList.IPagedList<MVC_projekt.Models.AuthorViewModel>
@{
    ViewBag.Title = "Search";
}

<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

<h2>Search Author</h2>

@Html.Partial("_SearchPartial")


@using (Html.BeginForm("Author", "BookItems",FormMethod.Get))
{
    <p>
        Find: @Html.TextBox("SearchString")
        <input type="submit" value="Search" name="submit" class="btn btn-default" />
        
    </p>
}
@if (User.Identity.IsAuthenticated)
{
    @Html.ActionLink("Save search result", "Author", new { save = true }, new { @class = "btn btn-info" })
}

<br />
<br />

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model[0].FullName)
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FullName)
                @Html.ActionLink(item.BooksNumber.ToString(), "BooksAuthor", new {id = item.ID}, new {@class = "badge"})
            </td>
        </tr>
    }

</table>

<div>
    <br />
    @Html.PagedListPager(Model, page => Url.Action("Index", new { page }))
    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
</div>

MVC_projekt/Views/BookItems/Books.cshtml
@using PagedList.Mvc
@model PagedList.IPagedList<MVC_projekt.Models.BookItemViewModel>

@{
    ViewBag.Title = "Books";
}
<br/>
@Html.Partial("_SearchPartial")

<h2>@ViewBag.Category</h2>



<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model[0].Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model[0].ISBN)
        </th>
        <th>
            @Html.DisplayNameFor(model => model[0].Publisher)
        </th>
        <th>
            @Html.DisplayNameFor(model => model[0].ReleaseDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model[0].Amount)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ISBN)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Publisher)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ReleaseDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AvailableNumber)/
                @Html.DisplayFor(modelItem => item.Amount)
            </td>
            <td>
                @Html.ActionLink("Details", "Details", new { id = item.ID }, new { @class = "btn btn-info" })
            </td>
            @if (User.IsInRole("Admin") || User.IsInRole("Employee"))
                {
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.ID }, new { @class = "btn btn-default" })
                </td>
                <td>
                    @Html.ActionLink("Delete", "Delete", new { id = item.ID }, new { @class = "btn btn-danger" })
                </td>
            }
        </tr>
    }

</table>

<div>
    <br/>
    @Html.PagedListPager(Model, page => Url.Action("Index", new {page}))
    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
</div>

MVC_projekt/Views/BookItems/Index.cshtml
@using PagedList.Mvc
@model PagedList.IPagedList<MVC_projekt.Models.BookItem>
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Index";
}
<br/>
@Html.Partial("_SearchPartial")

@if (User.IsInRole("Admin") || User.IsInRole("Admin"))
{
    <p>
        @Html.ActionLink(@Resources.Global.Add, "Create", null, new { @class = "btn btn-warning" })
    </p>
}

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model[0].AuthorGroups.Single(x=>x.Author.FullName != null).Author.FullName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model[0].Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model[0].Publisher)
        </th>
        <th>
            @Html.DisplayNameFor(model => model[0].ReleaseDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model[0].Category.Name)
        </th>
        <th></th>
        @if (User.IsInRole("Admin") || User.IsInRole("Employee"))
        {
            <th></th>
            <th></th>
        }
    </tr>

    @foreach (var item in Model) {
        <tr>
            <td>
                @foreach (var arg in item.AuthorGroups)
                {
                    @Html.DisplayFor(modelItem => arg.Author.FullName)
                    <br/>
                }
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Publisher)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ReleaseDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Category.Name)
            </td>
            <td>
                @Html.ActionLink(@Resources.Global.Details, "Details", new { id = item.BookItemID }, new { @class = "btn btn-info" })
            </td>
            @if (User.IsInRole("Admin") || User.IsInRole("Employee"))
            {
                <td>
                    @Html.ActionLink(@Resources.Global.Edit, "Edit", new { id = item.BookItemID }, new { @class = "btn btn-default" })
                </td>
                <td>
                    @Html.ActionLink(@Resources.Global.Delete, "Delete", new { id = item.BookItemID }, new { @class = "btn btn-danger" })
                </td>
            }
        </tr>
    }

</table>

<div>
    <br />
    @Html.PagedListPager(Model, page => Url.Action("Index", "BookItems", new { page }))
    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
</div>

MVC_projekt/Views/BookItems/Isbn.cshtml
@using MVC_projekt.Controllers
@using PagedList.Mvc
@model PagedList.IPagedList<MVC_projekt.Models.BookItemViewModel>
@{
    ViewBag.Title = "Search";
}

<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

<h2>Search ISBN</h2>

@Html.Partial("_SearchPartial")


@using (Html.BeginForm("Isbn", "BookItems", FormMethod.Get))
{
    <p>
        Find: @Html.TextBox("SearchString")
        <input type="submit" value="Search" name="submit" class="btn btn-default" />

    </p>
}
@if (User.Identity.IsAuthenticated)
{
    @Html.ActionLink("Save search result", "Isbn", new { save = true }, new { @class = "btn btn-info" })
}
<br />
<br />

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model[0].Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model[0].ISBN)
        </th>
        <th>
            @Html.DisplayNameFor(model => model[0].Publisher)
        </th>
        <th>
            @Html.DisplayNameFor(model => model[0].ReleaseDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model[0].Amount)
        </th>
        <th></th>
        @if (User.IsInRole("Admin") || User.IsInRole("Employee"))
        {
            <th></th>
            <th></th>
        }
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ISBN)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Publisher)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ReleaseDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AvailableNumber)/
                @Html.DisplayFor(modelItem => item.Amount)
            </td>
            <td>
                @Html.ActionLink("Details", "Details", new {id = item.ID}, new {@class = "btn btn-info"})
            </td>
            @if (User.IsInRole("Admin") || User.IsInRole("Employee"))
                {
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.ID }, new { @class = "btn btn-default" })
                </td>
                    <td>
                        @Html.ActionLink("Delete", "Delete", new { id = item.ID }, new { @class = "btn btn-danger" })
                    </td>
            }
        </tr>
    }

</table>

<div>
    <br />
    @Html.PagedListPager(Model, page => Url.Action("Index", new { page }))
    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
</div>

MVC_projekt/Views/BookItems/Label.cshtml
@using MVC_projekt.Controllers
@using PagedList.Mvc
@model PagedList.IPagedList<MVC_projekt.Models.LabelViewModel>
@{
    ViewBag.Title = "Search";
}

<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

<h2>Search Label</h2>

@Html.Partial("_SearchPartial")


@using (Html.BeginForm("Label", "BookItems", FormMethod.Get))
{
    <p>
        Find: @Html.TextBox("SearchString")
        <input type="submit" value="Search" name="submit" class="btn btn-default" />

    </p>
}
@if (User.Identity.IsAuthenticated)
{
    @Html.ActionLink("Save search result", "Label", new { save = true }, new { @class = "btn btn-info" })
}
<br />
<br />

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model[0].Name)
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
                @Html.ActionLink(item.BooksNumber.ToString(), "BooksLabel", new {id = item.ID}, new {@class = "badge"})
            </td>
        </tr>
    }

</table>

<div>
    <br />
    @Html.PagedListPager(Model, page => Url.Action("Index", new { page }))
    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
</div>

MVC_projekt/Views/BookItems/Title.cshtml
@using MVC_projekt.Controllers
@using PagedList.Mvc
@model PagedList.IPagedList<MVC_projekt.Models.TitleViewModel>
@{
    ViewBag.Title = "Search";
}

<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

<h2>Search Title</h2>

@Html.Partial("_SearchPartial")


@using (Html.BeginForm("Title", "BookItems", FormMethod.Get))
{
    <p>
        Find: @Html.TextBox("SearchString")
        <input type="submit" value="Search" name="submit" class="btn btn-default" />

    </p>
}
@if (User.Identity.IsAuthenticated)
{
    @Html.ActionLink("Save search result", "Title", new { save = true }, new { @class = "btn btn-info" })
}
<br />
<br />

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model[0].Title)
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
                @Html.ActionLink(item.BooksNumber.ToString(), "BooksTitle", new {id = item.Title}, new {@class = "badge"})
            </td>
        </tr>
    }

</table>

<div>
    <br />
    @Html.PagedListPager(Model, page => Url.Action("Index", new { page }))
    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
</div>